const PAGES = {
  ROOT: '/autismedu',
  HOME: '/home-page',
  LOGIN: '/login',
  DASHBOARD: '/admin/dashboard',
  USERMANAGEMENT: '/admin/user-management',
  ROLECLAIMMANAGEMENT: '/admin/role-claim-management',
  FORGOTPASSWORD: '/forgot-password',
  REGISTER: '/register',
  RESETPASSWORD: '/reset-password',
  CONFIRMREGISTER: '/confirm-register',
  LISTCENTER: '/list-center',
  LISTTUTOR: '/list-tutor',
  TUTORPROFILE: '/tutor-profile/:id',
  TUTORPROFILEUPDATE: '/tutor-profile-update/:id',
  TUTORREGISTRATIONMANAGEMENT: '/admin/tutor-registration-management',
  TUTOR_REGISTRATION_DETAIL: '/admin/tutor-registration-management/:id',
  TUTORREGISTRATION: '/autismtutor/tutor-registration',
  MY_STUDENT: '/autismtutor',
  STUDENT_DETAIL: '/autismtutor/student-detail/:id',
  TUTOR_SETTING: '/autismtutor/tutor-setting',
  LOGIN_OPTION: '/login-option',
  TUTOR_LOGIN: '/autismtutor/tutor-login',
  TUTOR_REQUEST: '/autismtutor/tutor-request',
  REGISTER_OPTION: '/register-option',
  MY_CHILDREN: '/my-childlren',
  CALENDAR: '/autismtutor/calendar',
  PARENT_PROFILE: '/my-profile',
  CHANGE_PASSWORD: '/change-password',
  ASSESSMENT_MANAGEMENT: '/admin/assessment-management',
  ASSESSMENT_CREATION: '/admin/assessment-creation',
  CERTIFICATE_DETAIL: '/autismtutor/certificate-detail/:id',
  STUDENT_CREATION: '/autismtutor/create-student-profile',
  APPROVE_STUDENT_PROFILE: '/approve-student-profile/:id',
  EXERCISE_MANAGEMENT: '/autismtutor/exercise',
  MY_TUTOR: '/my-tutor',
  MY_TUTOR_DETAIL: '/my-tutor/:id',
  TUTOR_REQUEST_HISTORY: '/request-history',
  LOGIN_ADMIN: '/admin/login',
  PAYMENT_PACKAGE_MANAGEMENT: '/admin/payment-package-management',
  SCORE_RANGE: '/admin/assessment_score_range',
  BLOG_MANAGEMENT: '/admin/blog-management',
  BLOG_CREATION: '/admin/blog-creation',
  BLOG_LIST: '/list-blogs',
  BLOG_DETAIL: '/list-blogs/:id',
  PAYMENT_PACKAGE: '/autismtutor/payment-package',
  PAYMENT_PACKAGE_FOCUS: '/autismtutor/payment-package-focus',
  PERSONAL_INFORMATION: '/admin/personal-information',

  BLOG_EDIT: '/admin/blog-management/edit/:id',
  REPORT_TUTOR_MANAGEMENT: '/admin/report-tutor-management',
  REPORT_TUTOR_DETAIL: '/admin/report-tutor-management/detail/:id',

  CERTIFICATE_MANAGEMENT: '/admin/certificate-management',
  CURRICULUM_MANAGEMENT: '/admin/curriculum-management',
  WORK_EXPERIENCE_MANAGEMENT: '/admin/work-experience-management',
  EXERCISE_TYPE_MANAGEMENT: '/admin/exercise-type-management',

  PAYMENT_HISTORY_TUTOR: '/autismtutor/payment-history',
  PAYMENT_HISTORY_ADMIN: '/admin/payment-history',

  PARENT_TUTOR_MAMAGEMENT: '/admin/parent-tutor-management',
  ADMIN_TUTOR_PROFILE: '/admin/tutor-profile/:id',
  ADMIN_PARENT_PROFILE: '/admin/parent-profile/:id',
  ADMIN_REPORT_REVIEW: '/admin/report-review-management',
  REPORT_REVIEW_DETAIL: '/admin/report-review-management/:id',

  CHANGE_PASSWORD_TUTOR: '/autismtutor/change-password',
  ASSESSMENT_GUILD: '/autismtutor/assessment-guild',
  ASSESSMENT_GUILD_CLIENT: '/assessment-guild',
};

export default PAGES;