//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutismEduConnectSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutismEduConnectSystem.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn đang bị khóa..
        /// </summary>
        public static string ACCOUNT_IS_LOCK_MESSAGE {
            get {
                return ResourceManager.GetString("ACCOUNT_IS_LOCK_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm role user cho người dùng.
        /// </summary>
        public static string ADD_ROLE_USER_TO_USER {
            get {
                return ResourceManager.GetString("ADD_ROLE_USER_TO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại khoảng điểm đánh giá từ {0} - {1}.
        /// </summary>
        public static string ASSESSMENT_SCORE_RANGE_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("ASSESSMENT_SCORE_RANGE_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch học ngày {0} vào khung giờ {1}-{2} đã được gán bài tập..
        /// </summary>
        public static string ASSIGNED_EXERCISE_NOTIFICATION {
            get {
                return ResourceManager.GetString("ASSIGNED_EXERCISE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đánh giá hoặc bạn không có quyền thay đổi đánh giá này.
        /// </summary>
        public static string BAD_ACTION_REVIEW {
            get {
                return ResourceManager.GetString("BAD_ACTION_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không hợp lệ.
        /// </summary>
        public static string BAD_REQUEST_MESSAGE {
            get {
                return ResourceManager.GetString("BAD_REQUEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể {0} vì {1} đang không {2}.
        /// </summary>
        public static string CANNOT_ACTION {
            get {
                return ResourceManager.GetString("CANNOT_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm {0} cho người dùng với vai trò {1}..
        /// </summary>
        public static string CANNOT_ADD_ROLE {
            get {
                return ResourceManager.GetString("CANNOT_ADD_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không thể lớn hơn {1}.
        /// </summary>
        public static string CANNOT_GREATER {
            get {
                return ResourceManager.GetString("CANNOT_GREATER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật. Vì {0} đang không ở trạng thái chờ.
        /// </summary>
        public static string CANNOT_UPDATE_BECAUSE_PENDING {
            get {
                return ResourceManager.GetString("CANNOT_UPDATE_BECAUSE_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại.
        /// </summary>
        public static string CHANGE_PASS_FAIL {
            get {
                return ResourceManager.GetString("CHANGE_PASS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng chỉ của bạn đã {0}.
        /// </summary>
        public static string CHANGE_STATUS_CERTIFICATE_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_CERTIFICATE_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khung chương trình của bạn đã {0}.
        /// </summary>
        public static string CHANGE_STATUS_CURRICULUM_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_CURRICULUM_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của bạn đã {0}.
        /// </summary>
        public static string CHANGE_STATUS_PROFILE_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_PROFILE_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phụ huynh {0} vừa {1} hồ sơ học sinh của bạn..
        /// </summary>
        public static string CHANGE_STATUS_STUDENT_PROFILE_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_STUDENT_PROFILE_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu dạy học của bạn {0} bởi {1}.
        /// </summary>
        public static string CHANGE_STATUS_TUTOR_REQUEST_PARENT_NOTIFICATION {
            get {
                return ResourceManager.GetString("CHANGE_STATUS_TUTOR_REQUEST_PARENT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia sư {0} vừa tạo một sổ liên lạc mới.
        /// </summary>
        public static string CREATE_PROGRESS_REPORT_PARENT_NOTIFICATION {
            get {
                return ResourceManager.GetString("CREATE_PROGRESS_REPORT_PARENT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia sư {0} vừa tạo một hồ sơ học sinh cho con  của bạn. Vui lòng xác nhận thông tin học sinh.
        /// </summary>
        public static string CREATE_STUDENT_PROFILE_PARENT_NOTIFICATION {
            get {
                return ResourceManager.GetString("CREATE_STUDENT_PROFILE_PARENT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; đã tồn tại.
        /// </summary>
        public static string DATA_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("DATA_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại buổi học tiếp theo đang được gán bài tập giống buổi học này. Bạn hãy cân nhắc gán lại bài tập khác..
        /// </summary>
        public static string DUPPLICATED_ASSIGN_EXERCISE {
            get {
                return ResourceManager.GetString("DUPPLICATED_ASSIGN_EXERCISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại trên hệ thống.
        /// </summary>
        public static string EMAIL_EXISTING_MESSAGE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTING_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác thực email.
        /// </summary>
        public static string EMAIL_NOT_CONFIRM {
            get {
                return ResourceManager.GetString("EMAIL_NOT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch học ngày {0} vào khung giờ {1}-{2} chưa được gán bài tập..
        /// </summary>
        public static string EXERCISE_NOT_ASSIGNED_NOTIFICATION {
            get {
                return ResourceManager.GetString("EXERCISE_NOT_ASSIGNED_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập vào tài nguyên..
        /// </summary>
        public static string FORBIDDEN_MESSAGE {
            get {
                return ResourceManager.GetString("FORBIDDEN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng Google không thể đối mật khẩu.
        /// </summary>
        public static string GG_CANNOT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("GG_CANNOT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng Google không thể truy cập quên mật khẩu..
        /// </summary>
        public static string GOOGLE_USER_INVALID_FORGOT_PASSWORD_MESSAGE {
            get {
                return ResourceManager.GetString("GOOGLE_USER_INVALID_FORGOT_PASSWORD_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đang trong trạng thái chờ..
        /// </summary>
        public static string IN_STATUS_PENDING {
            get {
                return ResourceManager.GetString("IN_STATUS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống. Vui lòng thử lại sau!.
        /// </summary>
        public static string INTERNAL_SERVER_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("INTERNAL_SERVER_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIên kết đã hết hạn..
        /// </summary>
        public static string LINK_EXPIRED_MESSAGE {
            get {
                return ResourceManager.GetString("LINK_EXPIRED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập..
        /// </summary>
        public static string LOGIN_WRONG_SIDE {
            get {
                return ResourceManager.GetString("LOGIN_WRONG_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhập đủ dữ liệu {0} và {1}.
        /// </summary>
        public static string MISSING_2_INFORMATIONS {
            get {
                return ResourceManager.GetString("MISSING_2_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhập đủ dữ liệu {0}.
        /// </summary>
        public static string MISSING_INFORMATION {
            get {
                return ResourceManager.GetString("MISSING_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cần phải thanh toán. Vui lòng thanh toán để tiếp tục..
        /// </summary>
        public static string NEED_PAYMENT_MESSAGE {
            get {
                return ResourceManager.GetString("NEED_PAYMENT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có đánh giá mới từ phụ huynh.
        /// </summary>
        public static string NEW_REVIEW_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("NEW_REVIEW_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy &apos;{0}&apos;..
        /// </summary>
        public static string NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã quá thời hạn thay đổi sổ liên lạc.
        /// </summary>
        public static string PROGRESS_REPORT_MODIFICATION_EXPIRED {
            get {
                return ResourceManager.GetString("PROGRESS_REPORT_MODIFICATION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi với refresh token..
        /// </summary>
        public static string REFRESH_TOKEN_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã xảy ra lỗi khi đăng ký. Vui lòng thử lại sau..
        /// </summary>
        public static string REGISTER_FAILED_MESSAGE {
            get {
                return ResourceManager.GetString("REGISTER_FAILED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch học ngày {0} vào khung giờ {1}-{2} đã được đánh giá.
        /// </summary>
        public static string SCHEDULE_UPDATE_NOTIFICATION {
            get {
                return ResourceManager.GetString("SCHEDULE_UPDATE_NOTIFICATION", resourceCulture);
            }
        }
         /// <summary>

        ///   Looks up a localized string similar to Gia sư {0} đã kết thúc dạy trẻ {1}..
        /// </summary>
        public static string STOP_TUTORING {
            get {
                return ResourceManager.GetString("STOP_TUTORING", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Quá hạn xét duyệt hồ sơ học sinh.
        /// </summary>
        public static string STUDENT_PROFILE_EXPIRED {
            get {
                return ResourceManager.GetString("STUDENT_PROFILE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bị trùng với khung giờ đã tồn tại {1}-{2}.
        /// </summary>
        public static string TIMESLOT_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("TIMESLOT_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token đã hết hạn,.
        /// </summary>
        public static string TOKEN_EXPIRED_MESSAGE {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã là gia sư hoặc đơn đăng ký làm gia sư đang chờ xử lý.
        /// </summary>
        public static string TUTOR_REGISTER_REQUEST_EXIST_OR_IS_TUTOR {
            get {
                return ResourceManager.GetString("TUTOR_REGISTER_REQUEST_EXIST_OR_IS_TUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có yêu cầu mới từ phụ huynh {0}.
        /// </summary>
        public static string TUTOR_REQUEST_TUTOR_NOTIFICATION {
            get {
                return ResourceManager.GetString("TUTOR_REQUEST_TUTOR_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật trạng thái thành đang xử lý!.
        /// </summary>
        public static string TUTOR_UPDATE_STATUS_IS_PENDING {
            get {
                return ResourceManager.GetString("TUTOR_UPDATE_STATUS_IS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng phải đăng nhập.
        /// </summary>
        public static string UNAUTHORIZED_MESSAGE {
            get {
                return ResourceManager.GetString("UNAUTHORIZED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gia sư {0} vừa cập nhật sổ liên lạc từ ngày {1} đến ngày {2}.
        /// </summary>
        public static string UPDATE_PROGRESS_REPORT_PARENT_NOTIFICATION {
            get {
                return ResourceManager.GetString("UPDATE_PROGRESS_REPORT_PARENT_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không có vai trò nào!.
        /// </summary>
        public static string USER_HAVE_NO_ROLE {
            get {
                return ResourceManager.GetString("USER_HAVE_NO_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đang bị khóa.
        /// </summary>
        public static string USER_IS_LOCKED_OUT {
            get {
                return ResourceManager.GetString("USER_IS_LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email hoặc mật khẩu không đúng..
        /// </summary>
        public static string USERNAME_PASSWORD_INVALID_MESSAGE {
            get {
                return ResourceManager.GetString("USERNAME_PASSWORD_INVALID_MESSAGE", resourceCulture);
            }
        }
    }
}
