//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("backend_api.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>        

		///   Looks up a localized string similar to Thêm role user cho người dùng.
        /// </summary>
        public static string ADD_ROLE_USER_TO_USER {
            get {
                return ResourceManager.GetString("ADD_ROLE_USER_TO_USER", resourceCulture);
            }
        }
        

        /// <summary>
		
        ///   Looks up a localized string similar to Đã tồn tại khoảng điểm đánh giá từ {0} - {1}.
        /// </summary>
        public static string ASSESSMENT_SCORE_RANGE_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("ASSESSMENT_SCORE_RANGE_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đánh giá hoặc bạn không có quyền thay đổi đánh giá này.
        /// </summary>
        public static string BAD_ACTION_REVIEW {
            get {
                return ResourceManager.GetString("BAD_ACTION_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; không hợp lệ.
        /// </summary>
        public static string BAD_REQUEST_MESSAGE {
            get {
                return ResourceManager.GetString("BAD_REQUEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm {0} cho người dùng với vai trò {1}..
        /// </summary>
        public static string CANNOT_ADD_ROLE {
            get {
                return ResourceManager.GetString("CANNOT_ADD_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thất bại.
        /// </summary>
        public static string CHANGE_PASS_FAIL {
            get {
                return ResourceManager.GetString("CHANGE_PASS_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; đã tồn tại.
        /// </summary>
        public static string DATA_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("DATA_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiện tại buổi học tiếp theo đang được gán bài tập giống buổi học này. Bạn hãy cân nhắc gán lại bài tập khác..
        /// </summary>
        public static string DUPPLICATED_ASSIGN_EXERCISE {
            get {
                return ResourceManager.GetString("DUPPLICATED_ASSIGN_EXERCISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa xác thực email.
        /// </summary>
        public static string EMAIL_NOT_CONFIRM {
            get {
                return ResourceManager.GetString("EMAIL_NOT_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng Google không thể đối mật khẩu.
        /// </summary>
        public static string GG_CANNOT_CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("GG_CANNOT_CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi hệ thống. Vui lòng thử lại sau!.
        /// </summary>
        public static string INTERAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("INTERAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải đăng nhập ở phía {0}.
        /// </summary>
        public static string LOGIN_WRONG_SIDE {
            get {
                return ResourceManager.GetString("LOGIN_WRONG_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhập đủ dữ liệu {0} và {1}.
        /// </summary>
        public static string MISSING_2_INFORMATIONS {
            get {
                return ResourceManager.GetString("MISSING_2_INFORMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không nhập đủ dữ liệu {0}.
        /// </summary>
        public static string MISSING_INFORMATION {
            get {
                return ResourceManager.GetString("MISSING_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy &apos;{0}&apos;..
        /// </summary>
        public static string NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quá hạn xét duyệt hồ sơ học sinh.
        /// </summary>
        public static string STUDENT_PROFILE_EXPIRED {
            get {
                return ResourceManager.GetString("STUDENT_PROFILE_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bị trùng với khung giờ đã tồn tại {1}-{2}.
        /// </summary>
        public static string TIMESLOT_DUPLICATED_MESSAGE {
            get {
                return ResourceManager.GetString("TIMESLOT_DUPLICATED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã là gia sư hoặc đơn đăng ký làm gia sư đang chờ xử lý.
        /// </summary>
        public static string TUTOR_REGISTER_REQUEST_EXIST_OR_IS_TUTOR {
            get {
                return ResourceManager.GetString("TUTOR_REGISTER_REQUEST_EXIST_OR_IS_TUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật trạng thái thành đang xử lý!.
        /// </summary>
        public static string TUTOR_UPDATE_STATUS_IS_PENDING {
            get {
                return ResourceManager.GetString("TUTOR_UPDATE_STATUS_IS_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không có vai trò nào!.
        /// </summary>
        public static string USER_HAVE_NO_ROLE {
            get {
                return ResourceManager.GetString("USER_HAVE_NO_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đang bị khóa.
        /// </summary>
        public static string USER_IS_LOCKED_OUT {
            get {
                return ResourceManager.GetString("USER_IS_LOCKED_OUT", resourceCulture);
            }
        }
    }
}
