version: '3.4'

services:
  autismeduconnectsystem:
    image: ${DOCKER_REGISTRY-}autismeduconnectsystem
    container_name: backend-aecs
    environment:
      - ASPNETCORE_HTTP_PORT=5000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=sendotp1234@gmail.com
      - SMTP_PASS=ifeahpwziexwuuqo
    build:
      context: .
      dockerfile: AutismEduConnectSystem/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    restart: always 
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456@
    ports:
      - "1433:1433"
    networks:
      - app-network
  react:
    build:
      context: ./SEP490_AutismEdu_FE
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173" 
    networks:
      - app-network
    depends_on:
      - autismeduconnectsystem
networks:
  app-network:
    driver: bridge