version: '3.4'

services:
  autismeduconnectsystem:
    image: ${DOCKER_REGISTRY-}autismeduconnectsystem
    container_name: backend-aecs
    environment:
      - ASPNETCORE_HTTP_PORT=5000
    ports:
      - "5000:5000"  # For your application HTTP
      - "25:25"      # SMTP standard port
      - "587:587"    # SMTP submission port (for sending emails securely)
      - "465:465"    # SMTP over SSL (alternative for secure email sending)
      - "2525:2525"  # Alternative SMTP port (used by some email providers)
    build:
      context: .
      dockerfile: AutismEduConnectSystem/Dockerfile
    depends_on:
      - db
    networks:
      - app-network
    restart: always 
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456@
    ports:
      - "1433:1433"
    networks:
      - app-network
  react:
    build:
      context: ./SEP490_AutismEdu_FE
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173" 
    networks:
      - app-network
    depends_on:
      - autismeduconnectsystem
networks:
  app-network:
    driver: bridge